public virtual class CaseWrapper {
    
public class CaseWrapper1{
        Public string Name;
        Public string id;
        Public string email;
        Public string gender;
         Public AdressWrapper Address;
        Public PhoneWrapper phone;

    }
    
     public class PhoneWrapper{
         Public string mobile;
         Public string home;
         Public string office;
     }
    
    public class AdressWrapper{
        Public string address1;
        Public string street;
        Public string country;
        
    }
}