public class OppApexClass {
    
    /*Public string NameAccVar;
    Public string NameOppVar;
    Public id Accid;
    
    public void Accountcre(){
        Account Acc = New Account();
        Acc.Name = NameAccVar;
        Insert Acc;      
        OppCre(Acc.Id);

            }
    public void OppCre(id Accid){
        Opportunity Opp = New Opportunity();
        Opp.Name = NameOppVar;
        Opp.CloseDate= date.today();
        opp.StageName = 'Closed won';
        opp.AccountId = Accid;
        Insert Opp;      
        
    }
   */ 
}